In [47]:
import seaborn as sns
%matplotlib inline
import pandas as bb
import warnings
warnings.filterwarnings("ignore")

######## importing the dataset using Pandas and showing head and info
db=bb.read_csv(r'C:\ya1\a1\titanic-passengers.csv')
db.dropna()
db.head()

PassengerId Survived  Pclass                                 Name     Sex  \
0          343       No       2                      Mr. Erik Gustaf    male   
1           76       No       3                    Mr. Sigurd Hansen    male   
2          641       No       3                       Mr. Hans Peder    male   
3          568       No       3   Mrs. Nils (Alma Cornelia Berglund)  female   
4          672       No       1                         Mr. Thornton    male   

    Age  SibSp  Parch     Fare  Cabin Embarked  
0  28.0      0      0  13.0000    NaN        S  
1  25.0      0      0   7.6500  F G73        S  
2  20.0      0      0   7.8542    NaN        S  
3  29.0      0      4  21.0750    NaN        S  
4  31.0      1      0  52.0000    B71        S

In [48]:
db['Survived'] = db['Survived'].str.replace('Yes', '1')
db['Survived'] = db['Survived'].str.replace('No', '0')
db['Survived']=db['Survived'].astype(str).astype(int)

In [49]:
db['Sex'] = db['Sex'].str.replace('female', '1')
db['Sex'] = db['Sex'].str.replace('male', '0')
db['Sex']=db['Sex'].astype(str).astype(int)
db['Sex'].unique()

array([0, 1])

In [50]:
X = db[['Pclass','Fare','Sex']]
y = db['Survived']
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

X_train


Pclass    Fare  Sex
140       2  26.250    1
439       3   7.750    1
817       2  26.000    1
378       3  15.500    1
491       3  69.550    1
..      ...     ...  ...
835       2  13.000    1
192       2  26.000    1
629       3  17.400    1
559       3   7.775    0
684       3   7.225    0

[712 rows x 3 columns]

In [53]:

print(X_train.shape, y_train.shape, X_test.shape)

(712, 3) (712,) (179, 3)


In [56]:
# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

acc_log = round(regressor.score(X_train, y_train) * 100, 2)
acc_log

36.38

In [55]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)

acc_log = round(logreg.score(X_train, y_train) * 100, 2)
acc_log

77.81

In [65]:
# Support Vector Machines
from sklearn.svm import SVC, LinearSVC
svc = SVC()
svc.fit(X_train, y_train)
Y_pred = svc.predict(X_test)
acc_svc = round(svc.score(X_train, y_train) * 100, 2)
acc_svc

67.13

In [66]:
# KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier
values = {}
for val in range(1, 51):
    knn = KNeighborsClassifier(n_neighbors = val)
    knn.fit(X_train, y_train)
    Y_pred = knn.predict(X_test)
    acc = round(knn.score(X_train, y_train) * 100, 2)
    values[val] = acc

acc

69.38

In [67]:
from sklearn.naive_bayes import GaussianNB
gaussian = GaussianNB()
gaussian.fit(X_train, y_train)
Y_pred = gaussian.predict(X_test)
acc_gaussian = round(gaussian.score(X_train, y_train) * 100, 2)
acc_gaussian

76.83

In [70]:
# Linear SVC
from sklearn.metrics import accuracy_score, mean_squared_error
linear_svc = LinearSVC()
linear_svc.fit(X_train, y_train)
Y_pred = linear_svc.predict(X_test)
acc_linear_svc = round(linear_svc.score(X_train, y_train) * 100, 2)
acc_linear_svc

77.67

In [77]:

#Validation
import numpy as np

from sklearn import metrics
print("MSE:",metrics.mean_squared_error(y_pred,y_test))
print("MAE:",metrics.mean_absolute_error(y_pred,y_test))
print("RMSE:",np.sqrt(metrics.mean_squared_error(y_pred,y_test)))
print("r2_score:",metrics.r2_score(y_pred,y_test))

MSE: 0.14062798834108786
MAE: 0.2852379621707908
RMSE: 0.3750039844336162
r2_score: -0.6799577459788468


In [82]:
from sklearn.metrics import roc_auc_score
pred_prob1 = logreg.predict_proba(X_test)

# auc scores
auc_score1 = roc_auc_score(y_test, pred_prob1[:,1])
auc_score1

0.8266879688802444

In [83]:
from sklearn.metrics import roc_curve
pred_prob2 = logreg.predict_proba(X_test)

# auc scores
Roc_score = roc_curve(y_test, pred_prob1[:,1])
Roc_score

(array([0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00847458, 0.00847458, 0.00847458, 0.00847458, 0.00847458,
        0.04237288, 0.04237288, 0.05084746, 0.06779661, 0.07627119,
        0.07627119, 0.08474576, 0.08474576, 0.09322034, 0.09322034,
        0.09322034, 0.09322034, 0.11016949, 0.11016949, 0.11864407,
        0.11864407, 0.13559322, 0.1779661 , 0.1779661 , 0.19491525,
        0.21186441, 0.22881356, 0.24576271, 0.26271186, 0.26271186,
        0.27118644, 0.31355932, 0.34745763, 0.36440678, 0.38983051,
        0.39830508, 0.40677966, 0.43220339, 0.48305085, 0.49152542,
        0.49152542, 0.5       , 0.52542373, 0.52542373, 0.53389831,
        0.55932203, 0.56779661, 0.58474576, 0.59322034, 0.61016949,
        0.62711864, 0.6440678 , 0.6440678 , 0.66101695, 0.72881356,
        0.79661017, 0.80508475, 0.80508475, 0.83050847, 0.8559322 ,
        0.86440678, 0.88135593, 0.88983051, 0.91525424, 0.98305085,
        0.98305085, 1.        ]),
 array([0.    